### ISSUE TITLE
Tracing example is broken

### ISSUE THREAD

**Issue by findingrish** [yokawasa/envoy-proxy-demos#1]
Getting following exception: `front-envoy_1    | Proto constraint validation failed (Using deprecated option 'envoy.api.v2.route.RouteMatch.regex' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.): regex: "/(service|trace)/blue"`

**Comment by yokawasa** [comment]
@rish691 My apologies for the late response. I'll check the issue and get back.

**Comment by yokawasa** [comment]
@rish691 
Please git pull the latest update on this project and try again. 
- https://github.com/yokawasa/envoy-proxy-demos/releases/tag/v1.0.0

Currently demo apps in the repositry are based on envoy api V1, therefore I specify the envoy api version to use for the demo app, NOT `latest` one as from envoy v1.13.0, v1 envoy api(s) are no longer supported.

Please open another issue if you find any other problems.

BTY, I am currently working to support envoy api v2.
